# docker-compose.prod.yml
services:
  postgres:
    image: postgres:15-alpine
    container_name: blogcms_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: md5
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - blog_network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U bloguser -d blogcms"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build: 
      context: ./backend
      dockerfile: dockerfile.prod
    container_name: blogcms_backend_prod
    env_file:
      - .env.prod.backend
    ports:
      - "3000:3000"
    networks:
      - blog_network

# Named volumes for data persistence
volumes:
  postgres_data:

# network for services communication
networks:
  blog_network:
    driver: bridge